modLoader = "javafml"
loaderVersion = "[36,)"
license = "GNU GPLv3"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''

[[dependencies.${mod_id}]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${mod_id}]]
modId = "portalmod"
mandatory= true
versionRange = "[1.0,)"
ordering = "BEFORE"
side = "BOTH"